# I'm using https://github.com/fgrehm/bindler
# It's for 'Dead easy Vagrant plugins management'
Vagrant.require_plugin("bindler")

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "symfony101.localhost"

  config.vm.network :private_network, ip: "10.10.10.10"
    config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--name", "symfony101"]
  end

  config.vm.synced_folder "../", "/var/www", id: "vagrant-root" , :nfs => (RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/)

  config.vm.provision :shell, :inline =>
    "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && sudo touch /apt-get-run; fi"


  config.vm.provision :shell, :inline => 'echo -e "mysql_root_password=root
controluser_password=awesome" > /etc/phpmyadmin.facts;'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.options = ['--verbose']
  end

  config.vm.provision :shell, :inline => 'sudo a2dissite default && sudo service apache2 reload'
end
